### ISSUE TITLE
qtranslate x integration

### ISSUE THREAD

**Issue by kosir** [livecomposer/Live-Composer#7]
it would be great if you would implement qtranslate x integration in tinymce for text module etc.
I'm using qtranslate x allover the site and I like your plugin, but it is almost not possible to create any translated content with modules, which doesn't provide translation interface.
thanks for listening
https://qtranslatexteam.wordpress.com/integration/

**Comment by pavot** [comment]
At Lumberman Designs we use WPML for translating websites created using Live Composer and it works perfectly.  

(I'm not LC developer, just user as yours)

**Comment by kosir** [comment]
@pavot thanks. I'll try wpml to see... anyway qtranslate x integration would be great since it is free plugin

**Comment by livecomposer** [comment]
Hi,

I'll test it out and see what can be done to make them work.

Regards,
Slobodan

**Comment by kosir** [comment]
Thanks!!!!

**Comment by livecomposer** [comment]
Looks like qTranslate is not compatible out of the box with a lot of plugins, many of them being rather popular like WooCommerce, Advanced Custom Fields, Gravity Forms, Yoast SEO, there are add-ons for those in order to become compatible.

So in the case of LC as well an add-on would be needed to make them compatible. but I'm unsure how would that work out exactly since LC does it's thing in the front-end while the qTranslate plugin's functionality is going on in the backend.

I will look into it and see what can be done, but it would be a rather complex task to take on and would need more users to come forward and ask for qTranslate compatibility in order to give it a bigger priority, there's a lot of tasks in the to do list which have higher prorirty at the moment.

**Comment by kosir** [comment]
thanks, yes, I'm aware it's a big task. hopefully somebody other will mark this as important.

**Comment by GabLeRoux** [comment]
Oh I was looking for this too. Just completed a full landing page and I realize I should have checked if it was compatible. Any reason why it's closed? A quick way to work around this would be to do the integration per page instead of per module, but I guess it would make it more painful for translators.
