### ISSUE TITLE
Proposal: New layout for Page Builder

### ISSUE THREAD

**Issue by NotAmaan** [livecomposer/Live-Composer#9]
I have always seen a great scope of improvement which can be added to LC's page builder layout so I have planned out a new layout for it.

**Here's the old layout:**
![Current Layout](http://i.imgur.com/xOzZh2g.png)

**Here's the new layout I'm proposing:**
![New Layout](http://i.imgur.com/QQ0qwad.png)

Benefits of the new layout:
* Less clicking: It sometimes gets annoying when finding a module, it takes alot of left and right clicks to find anything.
* WordPress-ish: LC's page builder is way too blue and once activated, it doesn't resemble to WordPress in any manner. This new layout would be white and grey, use WordPress's fonts and button styling. A bit like customizer.
* Reduce the JS used: LC currently uses 1 or maybe 2 js files just for the right and left scrolling which is an overkill. Since LC already loads owlcarousel, why not use owl carousel to handle the scrolling?
* See more Modules: Pretty obvious, it shows double the amount of modules than the old layout. Also, one click on the right/left arrow would scoll through all the modules currently visible instead of just a few ones like it is right now.
* Better identification: Since the icons in this layout are bigger, it would be easier for our eyes to remember and identify a module by its icon.

Potential questions:
* Would take more screen space: I don't think so since when we add a module and open the module's options, the builder height changes from 57px to 160px. The only difference now would be that the height would stay 160px in both scenarios, adding the module or configuring the module.
* Save/draft/close buttons: Icons could be a bit confusing at first but we could add clear tooltips on hover which would show what an icon does. Every icon would have a different color as well. We could also add small text to the icons but then we could only fit in the save and draft button there.

I could build this new layout once I hear back your opinions or maybe some others watching this repo as well. I would still need some help from you.

NOTE: The layout is pretty rough as it was a quick job but would look much neater in action. Also the icon is same for all modules, which is just for representation. Each module would have a different icon as they have right now).

**Comment by deptgraffig** [comment]
I've not digested what you're suggesting altogether just now, but could I add whether we actually need 'Icons' in the mix at all, and just have in alphabetical order - could we also have: basic, advanced and add-ons left module option panel - do we actually have to ever show all?

Just a couple of thoughts for now 
Thanks

**Comment by aman704** [comment]
@deptgraffig In general, yes alphabetical order would make sense.

You're right about basic, advanced radio buttons on the left but I'm not sure how one module would be assumed as a "Basic" module or "Advanced" module. The first set of modules as of now are: Module Area, Thumbnail, Title, The Content, Comments, Comment Form and I personally hardly or rather use them when building a page which is what I use LC most of the time. They sorting on the left could for example be:
* **All**
* **Page** (Modules we usually use for pages: Accordion, tabs, text area and all the others)
* **Posts** (Modules we usually use for pages: Accordion, tabs, text area and all the others)
* **Third Party** (Modules like Slider Revolution, Contact form, Woo and I'll also be building a new module for our menu plugin could be added to this filter)

Also, LC should be intelligent enough that if you're building a page using LC, the "Page" label should be selected by default instead of All and likewise for Posts.

Regarding need for icons, as I said its just for quick identification. Without them, the layout would look pretty dull and less intuitive. I've use the same icon in all modules but that's just for representation purpose. Its not a necessity altogether though.

**Comment by pavot** [comment]
I do strongly believe that Live Composer SHOULD NOT have it's own interface language. We should copy/adopt the Customizer panel design and UI. Only this way new users will get used to the Live Composer quickly as it will feels like something they already know/used.

**Comment by pavot** [comment]
One more note: horizontal panel scroll is always disaster for UX.

**Comment by pavot** [comment]
Here how I see it:
![new lc ui](https://cloud.githubusercontent.com/assets/1384471/12040198/0d83423c-ae24-11e5-994c-358c1d083b6b.png)

A few notes:
– Row is always first in the list
– Column is alway second in the list
– All the other modules are sorted based on usage. More often you use it higher the module placed.
– By default the modules sorted based on popularity that we can collect from our own usage after a few days of work.
– User can add the module using drag and drop or my clicking [Enter] after he found the module using search

**Comment by pavot** [comment]
Module properties should also looks the same as Customizer:

![lc module properties](https://cloud.githubusercontent.com/assets/1384471/12040252/a5230654-ae24-11e5-8f09-0ebc511227d9.png)

**Comment by livecomposer** [comment]
@aman704 @deptgraffig I've been actually thinking of getting rid of the scroller altogether. There will be something like a button for adding a module, clicking it will slide up a new area over the whole browser window with all the modules listed and organized properly. No need for any scrolling through them, all will be visible at the same time. As soon as you press the left mouse button on one of them ( to drag ) the area would slide down reveling the website and then you just drop the module where you need it.

@pavot That would be a completely different direction from what LC has been from the start, would be an overwrite of the whole system. Basically it would be getting rid of everything and creating a new plugin but with backwards compatibility so existing websites don't break. But the biggest issue would be the drastical change from what the users have been working with for the past 2 years, they won't like that at all.

**Comment by pavot** [comment]
@livecomposer you can get the same look by editing CSS only. No need to incorporate LC into Customizer for now. You don't even need to change HTML output.

Talking about what users get used to... I do think that by moving closer to the WP UI we are gaining more confidence for them. It's a basic rule in UX: you should build on what users already know minimizing new tricks they need to learn. It will boost adoption. I was looking my wife trying to create a simple page layout in LC and it was a very sad picture.

Any way my idea is just an idea. I believe it is valid as it's based on our clients support every day. It will be great to create to prototype what I proposed and ask a few WP users who not aware of LC to  accomplish a few simple tasks using old and new interface.

**Comment by pavot** [comment]
One of the client comment regarding horizontal scrolling we got today:
> One other little bit of feedback: although I like how your editor works, the horizontal scrolling has caused me to lose changes as if I scroll too far Chrome reads that as a ‘back’ gesture. I know I can disable that, actually I’ve just trained myself not to do it, but thought I’d flag it as a UX issue.

**Comment by livecomposer** [comment]
I'm pretty sure it can't be incorporated into Customizer. The Customizer works with iframes and drag/drop of elemenets won't work there. Also the Customizer likes to refresh the page a lot, so that won't work. That's just the main issues, there are others ( dynamicly loaded options without a refresh, Customizer being a bit slow when there are a lot of options... )

But moving closer to WP UI style would be possible. Just not sure how the existing users would react, if I was a user myself and something changed dramatically I wouldn't like it. I'll get used to it of course but wouldn't like it when it happens.

-

As for the wife, is she experienced with WordPress usage ( not LC, WordPres itself )? And did she try the interactive tutorials first, going straight into LC without the tutorials would definetely be confusing. 

-

About the back gesture, that's definetely a problem. How can I replicate that? I tried everything but no luck.

**Comment by lumberman** [comment]
I work form my MacBook 100% of time and don't use mouse. Touchpad comes with gestures. The horizontal scroling and swipe back (go back in history) are the same so many times I found myself loosing all the edits due to this problem. I trained myself to be careful with it. Looks like this users has the same issue.

We will invest some time in the end of Feb/March to come with CSS-only styling for the LC modules tray to make it looks like the Customizer UI. I don't care about current users' setiments as we expect to have multiply more theme users in the future and they will benefit from standartized interface. We can't progress without changing it. Probably after it's done you will decide to merge the changes in the main repo. Meanwhile we do work on making LC output 100% schema.org compatible.

Interface is a prety hard thing. It can be one of the reasons for the product success. I do believe that it should be clear how to create pages using LC without completing any tutorials for the users who already knows how WP works.

**Comment by livecomposer** [comment]
Ah, didn't know about that.

I'll check what exactly WordPress is using in the menus management, it shows a prompt on all attempts at leaving a page ( back button, link clicks, refresh... ) if you have a change made and will apply the same thing.

**Comment by aman704** [comment]
Hey guys,

With Slobodan's permission we're working on our own forked and rebranded version of LC for our themes. It basically has a different layout, WAY less styling options as that falls under the theme's domain, and we also have a target to reduce the JS and CSS by 30% and load just 1 JS and 1 CSS files.
Eitherways, here's the layout:
![Layout](http://i.imgur.com/FKuj9FB.png)

Reasoning behind the layout:
- Looks like Customizers so users don't feel that they just entered a new World
- Style Guide of WordPress Calypso so that users don't confuse it with Customizer because its not. 
- Also doesn't confuse users to look for Customizer options on the page builder screen.

Once again, thanks @livecomposer for letting us use LC's code, its a very neatly written plugin :)

Let me know what you guys think about it, I'll appreciate any feedback!

**Comment by deptgraffig** [comment]
Hey Guys - excited to see the path LC is going to go in the future! 

A while back Slobodan and I got into a conversation as to what I'd love to see changed/added to LC UI. The following was some thoughts I put together (please except that this UI option is **slightly over the top** with all the 'bells and whistles' on it so that I do not need to go elsewhere for a page builder/extra modules:
[live composer ui ideas 1](https://cloud.githubusercontent.com/assets/7841776/12919827/bb0bee56-cf3d-11e5-9539-29ef613acde3.jpg)

Aman704, not sure if you are mac based, but Vlad if you get the chance please take a look at Blocs from Norm if you have not already: http://blocsapp.com/ He has a trial version to play around with. Adding elements/module items can be a bit tricky (I'm not the best with short commands) however, the way items are styled, and more importantly to clarity of the UI panel on the left when selecting an element or module is wonderful - see here, bottom screen grab section:
[Uploading Live Composer UI Ideas 2.jpg…]()

It does remind me of the WP customiser but so much more polished.

Another item I like taken from the many page builders I use is the text styling pop up as shown here in the Cloudpress backend (and blocs actually):
[Uploading Live Composer UI Ideas 3.jpg…]()

Again, like Beaver Builder, this allows me to view in realtime changes to my text content, and indeed, is extended to other modules like images etc - it also does away with the need for any additional panels to enter text etc as you just type straight into text/heading module.

I also have some requests for the blank theme that Slobodan kindly produced for free, but maybe that should come later as I know you have a lot on your plates right now :)

I'll have to leave it there for now as trying to get a couple of print jobs (yes! Ink and Paper - lol) out the door for client!

Darron

**Comment by livecomposer** [comment]
Hi @aman704. We will be happy to see your changes/optimizations to the Live Composer code. If you can please share your repository with us make a commit if you feel it's ready for production? I can't recommend that we will be able to approve it, but we plan to have development branch for testing and evaluating of new ideas. 

I do think that the best way to move Live Composer forward will be to make it flexible/open for the developers like you. Probably, we can come with a solution when it will be possible for the theme developers to limit some styling like fonts or colors in favor of styling presets defined in the Customizer.

It's clear that Live Composer and Customizer can be better integrated in the future or even merged. The Customizer is much faster now and has better API. We will keep this direction in mind and discuss with you (developers).

Regarding interface update: I'm happy that idea with moving LC interface to more standardized look find your interest. Do you already have it coded or it's a mockup? 

Slobodan, had big concerns about changing UI for the current plugin users. On the other hand, the closer we keep our product to the WordPress standards (including UI/UX) the better adoption it will get among the users.

As I said before, we are going to have a dev branch for big changes and will test all the new features before committing into the main branch.

**Comment by livecomposer** [comment]
@deptgraffig thanks a lot for the ideas shared. I will check the application you recommended and come back to answer your message tomorrow. Need some time to think on all the ideas shared.

**Comment by deptgraffig** [comment]
No problem at all - speak soon :)

**Comment by aman704** [comment]
Hey @deptgraffig

Thank you for your comments!

The UI1 is nice but trust be, users are in for a breakdown after they see it for the first time ;)
Also, since I'm a laptop, I don't have this layout would take up a major part of the 13 inch screen I got. It'd look better on mac's screen and I think that's the dimension its designed for but then not everybody has it. Also there wouldn't be any purpose of atleast 1 of the sidebars at a give point of time, you would either be adding a module or customizing it. So showing both simultaneously even though you won't be using it wouldn't be the best idea IMO, but as you said its really something based on your preference so no questions there.

I've used blocsapp and it has a really cool interface, so does Squarespace and many other page builders but the layout I built is really reflecting WordPress. I could make it way more modern and polished but I wanted to keep the builder I'm working on as close to wordpress as possible.

@livecomposer assuming you're Vlad, I just wrote you a long email :)
You're right about LC and customizer being potentially merged but I'm not sure if you have anything in mind for dragging and dropping over iframes. One option could be widgets API but I'm not really a big fan of it. I'm also keeping an eye on this feature request https://github.com/bevacqua/dragula/issues/291 and if they implement it, maybe we could use it for LC.
I have the screenshot I sent you coded and working but I don't think it'd be just a CSS drop in as I've pretty much renamed all the classes as well as per BEM standards but I could definitely contribute to LC as well!

**Comment by deptgraffig** [comment]
Hi aman, as you mentioned this is the overkill version - in the sketch I've shown every possible panel idea open at the same time, but in fact, once you've added a module (like beaver builder) you would not see all the left panel and only part of the right styling panel depending on what element you select

**Comment by deptgraffig** [comment]
with regards that pull request - I like the idea of not needing to drag, could we not just select a row or column, click the module required and it occupies the active area automatically?

**Comment by deptgraffig** [comment]
I'm currently testing this page builder: https://pagebuildersandwich.com/ which has some nice user options
